### ISSUE TITLE
Thanks and TIL qpdf

### ISSUE THREAD

**Issue by marramgg** [wilfredwee/wilfred-TILs#1]
Hey, just wanted to let you know that your tip about decrypting a PDF really saved me tonight :)

TIL about qpdf!

In https://github.com/wilfredwee/wilfred-TILs/blob/master/command-line-pdf/decrypting-a-pdf-file-without-owner-password-on-the-command-line.md

Thanks! Feel free to close this :)

**Comment by wilfredwee** [comment]
Glad to hear that! You're welcome :)
